(function(App){
'use strict';
var LIMIT_BYTES=250*1024*1024;
var ITEM_LIMIT_BYTES=5*1024*1024;
var WARN_RATIO=.8;
function bytes(att){if(!att)return 0;if(Number.isFinite(att.size))return Math.max(0,Number(att.size));if(att.dataUrl)return String(att.dataUrl).length;return 0;}
function fmt(n){n=Math.max(0,Number(n)||0);if(n<1024)return n+' B';if(n<1048576)return (n/1024).toFixed(n<10240?1:0)+' KB';return (n/1048576).toFixed(n<10485760?1:0)+' MB';}
function stats(){var state=App.Storage&&App.Storage.getState?App.Storage.getState():{notes:[]};var total=0,photos=0,pdfs=0,items=[];(state.notes||[]).forEach(function(note){(note.attachments||[]).forEach(function(att){var s=bytes(att);total+=s;if(att.type==='image')photos++;if(att.type==='pdf')pdfs++;items.push({id:att.id,noteId:note.id,name:att.name||'Attachment',note:note.title||'Untitled note',size:s,type:att.type||'file',dataUrl:att.dataUrl||''});});});items.sort(function(a,b){return b.size-a.size;});return{total:total,limit:LIMIT_BYTES,remaining:Math.max(0,LIMIT_BYTES-total),ratio:total/LIMIT_BYTES,photos:photos,pdfs:pdfs,count:items.length,items:items};}
function canAdd(size){var s=Number(size)||0;var st=stats();if(s>ITEM_LIMIT_BYTES)return{ok:false,message:'This attachment is over the 5 MB limit after compression.'};if(st.total+s>LIMIT_BYTES)return{ok:false,message:'Attachment storage limit reached. Delete older attachments before adding more.'};if(st.total+s>LIMIT_BYTES*WARN_RATIO)return{ok:true,warn:true,message:'Storage is getting high. Consider deleting old attachments soon.'};return{ok:true,warn:false,message:''};}
function esc(x){return String(x||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');}
function section(){var st=stats();var pct=Math.min(100,Math.round(st.ratio*100));var cls=st.ratio>=.95?'danger':st.ratio>=WARN_RATIO?'warn':'ok';return '<div class="settings-section attachment-meter-section"><div class="settings-section-label">Attachments</div><div class="settings-row" style="flex-direction:column;align-items:stretch;gap:10px"><div style="display:flex;align-items:center;justify-content:space-between;gap:12px"><div><div class="settings-row-label">Storage Used</div><div class="settings-row-sub">'+fmt(st.total)+' / '+fmt(st.limit)+' safety limit</div></div><span class="attachment-meter-chip '+cls+'">'+pct+'%</span></div><div class="attachment-meter-bar"><span style="width:'+pct+'%"></span></div><div class="attachment-meter-grid"><div><b>'+st.photos+'</b><span>Photos</span></div><div><b>'+st.pdfs+'</b><span>PDFs</span></div><div><b>'+fmt(st.remaining)+'</b><span>Free</span></div></div><button class="btn btn-secondary btn-sm" onclick="App.AttachmentMeter.open()">Manage Storage</button></div></div>';}
function inject(){var pane=document.getElementById('pane-settings');if(!pane||!pane.classList.contains('active'))return;if(pane.querySelector('.attachment-meter-section'))return;var sections=pane.querySelectorAll('.settings-section');var target=sections[3]||sections[sections.length-1];if(target)target.insertAdjacentHTML('afterend',section());}
function itemByIds(noteId,attId){var state=App.Storage.getState();var note=(state.notes||[]).find(function(n){return n.id===noteId;});var att=note&&(note.attachments||[]).find(function(a){return a.id===attId;});return{note:note,att:att};}
function view(noteId,attId){var x=itemByIds(noteId,attId);if(!x.att||!x.att.dataUrl){App.showToast('Preview not available yet.','error');return;}if(x.att.type==='image'&&App.PhotoAttachments&&App.PhotoAttachments.openViewer){App.PhotoAttachments.openViewer(noteId,attId);return;}window.open(x.att.dataUrl,'_blank');}
function remove(noteId,attId){if(!confirm('Delete this attachment?'))return;var x=itemByIds(noteId,attId);if(!x.note)return;var kept=(x.note.attachments||[]).filter(function(a){return a.id!==attId;});App.Storage.updateNote(noteId,{attachments:kept});App.showToast('Attachment deleted','success');document.getElementById('attachment-meter-modal')?.remove();if(document.getElementById('note-modal'))document.getElementById('note-modal').remove();App.Notes&&App.Notes.render&&App.Notes.render();if(document.getElementById('pane-settings')&&document.getElementById('pane-settings').classList.contains('active')){App.Settings&&App.Settings.render&&App.Settings.render();setTimeout(open,120);} }
function open(){var st=stats();document.getElementById('attachment-meter-modal')?.remove();var rows=st.items.slice(0,25).map(function(i){return '<div class="attachment-meter-item"><div class="attachment-meter-main"><div class="settings-row-label">'+esc(i.name)+'</div><div class="settings-row-sub">'+esc(i.note).slice(0,70)+'</div><div class="settings-row-sub">'+fmt(i.size)+'</div></div><div class="attachment-meter-actions"><button class="btn btn-secondary btn-sm" onclick="App.AttachmentMeter.view(\''+i.noteId+'\',\''+i.id+'\')">View</button><button class="btn btn-danger btn-sm" onclick="App.AttachmentMeter.remove(\''+i.noteId+'\',\''+i.id+'\')">Delete</button></div></div>';}).join('')||'<div class="settings-row-sub">No attachments yet.</div>';var html='<div id="attachment-meter-modal" class="modal-backdrop" onclick="if(event.target===this)this.remove()"><div class="modal-sheet" style="max-height:82vh"><div class="modal-handle"></div><div class="modal-title">Manage Storage</div><div class="settings-row-sub" style="margin-bottom:12px">Using '+fmt(st.total)+' of '+fmt(st.limit)+'. Largest attachments shown first.</div><div class="attachment-meter-list">'+rows+'</div><div class="modal-actions sticky-actions"><button class="btn btn-secondary" onclick="document.getElementById(\'attachment-meter-modal\').remove()">Close</button></div></div></div>';document.body.insertAdjacentHTML('beforeend',html);}
function install(){if(window.__noteClipAttachmentMeterReady)return;window.__noteClipAttachmentMeterReady=true;inject();new MutationObserver(inject).observe(document.body,{childList:true,subtree:true});}
App.AttachmentMeter={stats:stats,canAdd:canAdd,formatBytes:fmt,open:open,view:view,remove:remove,LIMIT_BYTES:LIMIT_BYTES,ITEM_LIMIT_BYTES:ITEM_LIMIT_BYTES};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})(window.App=window.App||{});
