/* document-scanner.js — Stage 15 document scanner MVP */
(function(App){
'use strict';
var MAX_SIDE=1700;
var JPEG_QUALITY=.84;
function uid(){return 'scan_'+Date.now().toString(36)+Math.random().toString(36).slice(2,7);}
function esc(s){return String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');}
function readAsDataUrl(file){return new Promise(function(resolve,reject){var r=new FileReader();r.onload=function(){resolve(r.result);};r.onerror=reject;r.readAsDataURL(file);});}
function loadImage(src){return new Promise(function(resolve,reject){var img=new Image();img.onload=function(){resolve(img);};img.onerror=reject;img.src=src;});}
function chooseDocumentPhoto(){return new Promise(function(resolve){var input=document.createElement('input');input.type='file';input.accept='image/*';input.setAttribute('capture','environment');input.style.position='fixed';input.style.left='-9999px';input.addEventListener('change',function(){resolve(input.files&&input.files[0]?input.files[0]:null);input.remove();});document.body.appendChild(input);input.click();});}
async function enhanceImage(file){var src=await readAsDataUrl(file);var img=await loadImage(src);var w=img.width,h=img.height;var scale=Math.min(1,MAX_SIDE/Math.max(w,h));w=Math.round(w*scale);h=Math.round(h*scale);var canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;var ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,w,h);ctx.filter='contrast(1.12) brightness(1.04) saturate(0.92)';ctx.drawImage(img,0,0,w,h);return {dataUrl:canvas.toDataURL('image/jpeg',JPEG_QUALITY),width:w,height:h};}
function b64ToBinary(b64){return atob(b64.split(',')[1]||b64);}
function makePdfFromJpeg(jpegDataUrl,w,h){var imgBin=b64ToBinary(jpegDataUrl);var pageW=612;var pageH=Math.max(792,Math.round(pageW*h/w));if(pageH>1008){pageH=1008;pageW=Math.round(pageH*w/h);}var margin=18;var drawW=pageW-margin*2;var drawH=drawW*h/w;if(drawH>pageH-margin*2){drawH=pageH-margin*2;drawW=drawH*w/h;}var x=(pageW-drawW)/2;var y=(pageH-drawH)/2;var content='q\n'+drawW.toFixed(2)+' 0 0 '+drawH.toFixed(2)+' '+x.toFixed(2)+' '+y.toFixed(2)+' cm\n/Im0 Do\nQ\n';var objects=[];objects.push('1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n');objects.push('2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n');objects.push('3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 '+pageW+' '+pageH+'] /Resources << /XObject << /Im0 4 0 R >> >> /Contents 5 0 R >>\nendobj\n');objects.push('4 0 obj\n<< /Type /XObject /Subtype /Image /Width '+w+' /Height '+h+' /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length '+imgBin.length+' >>\nstream\n'+imgBin+'\nendstream\nendobj\n');objects.push('5 0 obj\n<< /Length '+content.length+' >>\nstream\n'+content+'endstream\nendobj\n');var pdf='%PDF-1.3\n';var offsets=[0];for(var i=0;i<objects.length;i++){offsets.push(pdf.length);pdf+=objects[i];}var xref=pdf.length;pdf+='xref\n0 '+(objects.length+1)+'\n0000000000 65535 f \n';for(var j=1;j<offsets.length;j++){pdf+=String(offsets[j]).padStart(10,'0')+' 00000 n \n';}pdf+='trailer\n<< /Size '+(objects.length+1)+' /Root 1 0 R >>\nstartxref\n'+xref+'\n%%EOF';return 'data:application/pdf;base64,'+btoa(pdf);}
function check(size){var c=App.AttachmentMeter&&App.AttachmentMeter.canAdd?App.AttachmentMeter.canAdd(size):null;if(!c)return true;if(!c.ok){App.showToast(c.message,'error');return false;}if(c.warn)App.showToast(c.message,'success');return true;}
async function scanToPdf(catId,noteId){var file=await chooseDocumentPhoto();if(!file)return;if(!file.type||!file.type.startsWith('image/')){App.showToast('Please choose an image.','error');return;}try{App.showToast('Scanning document…','success');var image=await enhanceImage(file);var pdfDataUrl=makePdfFromJpeg(image.dataUrl,image.width,image.height);if(!check(pdfDataUrl.length))return;var name='Scanned Document '+new Date().toLocaleDateString()+'.pdf';var att={id:uid(),type:'pdf',name:name,mime:'application/pdf',size:pdfDataUrl.length,dataUrl:pdfDataUrl,createdAt:new Date().toISOString(),source:'scan'};if(noteId){var state=App.Storage.getState();var note=state.notes.find(function(n){return n.id===noteId;});if(!note)return;var attachments=Array.isArray(note.attachments)?note.attachments.slice():[];attachments.push(att);App.Storage.updateNote(noteId,{attachments:attachments});App.showToast('Scan attached','success');App.Notes&&App.Notes.render&&App.Notes.render();setTimeout(function(){App.Notes&&App.Notes._editNote&&App.Notes._editNote(noteId);},120);return;}var noteObj=App.Storage.addNote({title:'Scanned Document',body:'',categoryId:catId||null,status:'active',attachments:[att]});App.showToast('Scan saved as PDF','success');App.Notes&&App.Notes.render&&App.Notes.render();setTimeout(function(){App.Notes&&App.Notes._editNote&&App.Notes._editNote(noteObj.id);},150);}catch(e){console.error('[DocumentScanner] failed',e);App.showToast('Scan could not be saved.','error');}}
function createScanNote(catId){scanToPdf(catId,null);}
function addScanToNote(noteId){scanToPdf(null,noteId);}
App.DocumentScanner={createScanNote:createScanNote,addScanToNote:addScanToNote};
})(window.App=window.App||{});
